name: Rails CI

# トリガーをmainに設定
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: reflecty_api_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1. リポジトリのコードをチェックアウトする
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Rubyのバージョンを設定する
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true # Gemのインストールをキャッシュして高速化

      # 3. データベースを作成・マイグレーションする
      - name: Setup database
        env:
          RAILS_ENV: test
          DATABASE_HOST: localhost # servicesで定義したpostgresを指す
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: password
        run: |
          cd reflecty-api
          bundle exec rails db:create
          bundle exec rails db:migrate

      # 4. RSpecテストを実行する
      - name: Run RSpec tests
        env:
          RAILS_ENV: test
          DATABASE_HOST: localhost
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: password
        run: |
          cd reflecty-api
          bundle exec rspec
